### ISSUE TITLE
Is it possible to use this with .vue extension?

### ISSUE THREAD

**Issue by prashantsharma** [dsznajder/vscode-react-javascript-snippets#144]
I can not use this plugin with .vue files. Any plans to add support for vue and html files.

**Comment by dsznajder** [comment]
@prashantsharma I will try to add some kind of options for that in the future, but currently, I do not have much time.

**Comment by Nick-HK** [comment]
@prashantsharma Interesting idea but I think it's better to separate it into another project like:

Vue: vscode-es7-javascript-vue-snippets
Angular: vscode-es7-javascript-angular-snippets

**Comment by dsznajder** [comment]
@Nick-HK I feel like this would be very hard to maintain especially when I have kinda limited time to do this. I'm currently working on the v4 version which will have dynamic options for defining supported extensions and other stuff that should be adjustable based on prettier / preferences. Stay tuned 👀
