### ISSUE TITLE
After last update  How to enable this extension back?

### ISSUE THREAD

**Issue by KostiantynO** [dsznajder/vscode-react-javascript-snippets#205]
After last update  How to enable this extension back?
It does not work now in win 10 VSCode !
If you try to use enf/anf or any other snippet - No suggestions showed in intelliSence dialog dropdown !

**Comment by mikededo** [comment]
Check the `React Snippets › Settings: Language Scopes` option in VSCode settings. Try adding the default value, which is: `typescript,typescriptreact,javascript,javascriptreact`.

If still does not work, check that the file type is detected by VSCode is the correct one. Autocomplete for javascript will not work unless it detects a javascript type of file. 

If still does not solve your issue, check that you have not set any configuration or similar that disabled the extension locally or even in the workspace.

**Comment by dsznajder** [comment]
@KostiantynO Sorry, I see that I missed `others` snippets for parsing. I also recommend you to restart VSCode as right now they are generated on js/ts file open. Released in `v4.0.3`

**Comment by KostiantynO** [comment]
Thank you very much! Now it works!
