### ISSUE TITLE
useState Snipet got removed in last checkin

### ISSUE THREAD

**Issue by stephan5463** [dsznajder/vscode-react-javascript-snippets#206]
it was removed in checkin d410801

was this intentional?

**Comment by ubaidjs** [comment]
facing same issue.

**Comment by dsznajder** [comment]
Yeah, it was removed as I thought of it as something unused and confusing with React API. I've added all of those with the additional suffix `Snippet` for easier recognition. Released in `v4.0.3`.

**Comment by ubaidjs** [comment]
@dsznajder 
On more thing you missed to fix is the capitalisation of of variable name after 'set'
![Screenshot 2022-01-20 at 5 12 37 PM](https://user-images.githubusercontent.com/38839145/150332822-ffbcaa4a-1933-4c7f-bb70-2fb26dc03567.png)
