### ISSUE TITLE
Bug (?): Extra line for snippets for v4+

### ISSUE THREAD

**Issue by Roman-Popov** [dsznajder/vscode-react-javascript-snippets#207]
Is it necessary?
I used to type `clg` for example.
The result for version 3+ was:
```
console.log(object)
```

Now, at current version I'm getting this:
```
console.log(object)

```
Looks like a bug, because I don't see extra line at `/src/sourceSnippets/console.ts ` but I see them at `https://github.com/dsznajder/vscode-react-javascript-snippets/blob/master/src/snippets/generated.json`
It's pretty annoying, could you please fix that?

**Comment by dsznajder** [comment]
@Roman-Popov should be resolved, sorry for this. Currently, snippets are dynamically generated based on settings / prettier integration so source "generated" differs from what is actually used. Skipped adding a line from default prettier settings and should be fixed in `v4.0.3`
