### ISSUE TITLE
Underscore snippets prefix no longer working

### ISSUE THREAD

**Issue by asdf1414** [dsznajder/vscode-react-javascript-snippets#208]
Updated today from v3.1.0 to v4.0.3 - Since the new update **I'm missing the underscore prefix for the snippets** (e.g. _rfce). I checked other versions in VScode and this "bug" seems to exist in v3.1.1 already, therefore I'm not quite sure whether it's a bug or just a removed feature.

**Comment by pmioduszewski** [comment]
Same issue 😢

**Comment by dsznajder** [comment]
#153 Working on that one. Will release a new version. After the update, take a look at Extension Settings as `importReactOnTop` variable was introduced
