### ISSUE TITLE
React Typescript Snippets not working

### ISSUE THREAD

**Issue by MuttakinHasib** [dsznajder/vscode-react-javascript-snippets#209]
`tsrafce` `tsrafc` etc. not working

**Comment by dsznajder** [comment]
@MuttakinHasib take a look at snippet settings and just enable `typescript` ones :) I Hope rest will work well 👀

**Comment by AntonOfTheWoods** [comment]
@dsznajder , thanks heaps for the plugin, but this is a huge breaking change for us Typescript users. Something in the changelog would have been much less confusing!

**Comment by dsznajder** [comment]
@AntonOfTheWoods There is a breaking major change. I also pre-generated `ts` snippets to be working in the same way. Not sure if it has regenerated itself. I will change the default value of snippet generation to true, which should resolve this issue
