### ISSUE TITLE
useStateSnippet no longer camelCases the callback function. v4.0.3

### ISSUE THREAD

**Issue by obriedan** [dsznajder/vscode-react-javascript-snippets#210]
First of all, love the addition of snippet to input! The latest release is no longer setting the callback to camel case.

![Screenshot_18](https://user-images.githubusercontent.com/46796944/150218536-66c2f4a7-1fc4-41b7-bb40-f74c5206e606.png)

Love the extension, just realised how much time it saves me.

**Comment by ubaidjs** [comment]
![Screenshot 2022-01-20 at 5 12 37 PM](https://user-images.githubusercontent.com/38839145/150336571-6f374301-a978-47b7-893b-6d0039929872.png)

**Comment by dsznajder** [comment]
released in `v4.1.0`

**Comment by iamrealmarsel** [comment]
@dsznajder snippets dont work in `v4.1.0`
