### ISSUE TITLE
Can't change Default Typescript Component PropsState Prefix

### ISSUE THREAD

**Issue by MuttakinHasib** [dsznajder/vscode-react-javascript-snippets#212]
`settings.json`

![image](https://user-images.githubusercontent.com/44552983/150341426-68a6d7eb-c64f-4e55-af0c-d35d1ebef701.png)

![image](https://user-images.githubusercontent.com/44552983/150341607-1da7dec7-a4f1-4110-b708-86b233632887.png)

**Comment by dsznajder** [comment]
@MuttakinHasib Fixed in `v4.1.0` as I forgot to implement this feature 😅

**Comment by henningeiben** [comment]
I just installed v4.1.0, but still I don't get interfaces in favor of types.

Also `reactSnippets.settings.prettierEnabled` doesn't seem to have an impact.
