### ISSUE TITLE
rafce snippet    " return<div></div> " in a single line. Can the div be in a braces by default? 

### ISSUE THREAD

**Issue by anilbdev** [dsznajder/vscode-react-javascript-snippets#213]
rafce snippet gives below code
import React from 'react';

function FirstPage() {
  return <div></div>;
}

export default FirstPage;

Previously return statement was like
 
return(
<div>
</div>
)

How can i change to old return format?

**Comment by dsznajder** [comment]
@anilbdev right now, a snippet is integrated with a prettier config. Take a look at settings disable `semiColons` option and restart vscode
