### ISSUE TITLE
One liner snippets with semiColons enabled produce unnecessary line

### ISSUE THREAD

**Issue by 314857493** [dsznajder/vscode-react-javascript-snippets#216]
![image](https://user-images.githubusercontent.com/34772902/150508681-02e36712-fee8-4168-9bdc-a05eedbeabb2.png)
when I use imp/ime/ima ,there is one ';' in the next line, is it normal?

**Comment by dsznajder** [comment]
No, it's bug related, thanks for sharing. Will tackle it on weekend

**Comment by 314857493** [comment]
> No, it's bug related, thanks for sharing. Will tackle it on weekend

copy that

**Comment by Spider101** [comment]
Any update on this? Not sure but I feel the `$0;` in this [line](https://github.com/dsznajder/vscode-react-javascript-snippets/blob/master/src/snippets/generated.json#L823) might be the culprit here.

**Comment by dsznajder** [comment]
@314857493 Fixed in v4.3.1
