### ISSUE TITLE
New Snippets and searh stop working since last update

### ISSUE THREAD

**Issue by PabloPenia** [dsznajder/vscode-react-javascript-snippets#222]
Hi, sorry I know there a lot of issues about this topic but I read all closed issues, the read me and the list of snippets and still can't use the snippets.

After update I could use for example the old `_rafce` as `rafce` and works perfectly but in the last two days stop working. Also the search shortcut, see the pictures
![150657348-4b6bcd7e-57e6-4647-8cc1-ea67f99e4a25](https://user-images.githubusercontent.com/88749586/150703197-efd0feee-7a71-429a-b819-a1eecd0fc880.png)
![Captura de pantalla_2022-01-23_20-43-51](https://user-images.githubusercontent.com/88749586/150703200-7c62614e-6cd1-4110-aacc-45b12e9f6783.png)
.

I use jsx format, but tested with JS and and can't use the snippets in any way these are my settings:

- Import React on Top > unchecked (checked gives the same result)
- Language scopes > typescript,typescriptreact,javascript,javascriptreact
- Prettier enabled > checked
- semicolons & and single quote > both checked

I tested bit different settings then reload, reinstall the extension but can't make it work

**Comment by BabkinAV** [comment]
I confirm the extension stopped working. Rolled back to 4.0.1 from marketplace version history, seems working fine now.

**Comment by aryankarim** [comment]
Same for me. I downgraded it to version 4.0.3 since the latest update isn't working.

**Comment by dsznajder** [comment]
Going to dive into this during the weekend and resolve a bunch of those issues as I have now knowledge and stuff to work with. Thanks for your patience and feedback!

**Comment by ShanuDey** [comment]
I am facing this same issue. Snippet suggestion is working after last update. Please have a look into this issue. BTW It was a awesome extension before this bug. :)

**Comment by xteqr1** [comment]
Underscore commands like '_rfce' don't work too.

**Comment by dsznajder** [comment]
@xteqr1 #223 #220 #215

**Comment by AlaaCherif** [comment]
yep same thing thing for me hope this gets fixed soon

**Comment by dsznajder** [comment]
@AlaaCherif Hope to release a new version by end of the week.

**Comment by Jaimesanchezgalvis** [comment]
same problem, thansk god i was think i jus me

**Comment by dsznajder** [comment]
@PabloPenia Fixed in v4.3.1
