### ISSUE TITLE
why append `Snippet` to every snippet 👎? 

### ISSUE THREAD

**Issue by HomyeeKing** [dsznajder/vscode-react-javascript-snippets#224]
the Vscode gives different Icon to differenciate snippet and api, why you append `Snippet` suffix👎? 
it really  really makes me **uncomfortable**, I **have to** adapt the new name to find the snippet....

**Comment by dsznajder** [comment]
@HomyeeKing to avoid auto-import confusion `Snippet` prefix was introduced to react hooks and only them. The rest of snippets should look the same as previously

**Comment by HomyeeKing** [comment]
@dsznajder  and no redux hooks snippet, what's this for, actually, I don't think this update is necessary, a lot of bad experience
