### ISSUE TITLE
PropTypes snippets line break

### ISSUE THREAD

**Issue by edvein-rin** [dsznajder/vscode-react-javascript-snippets#225]
Somewhere around a week ago I found that PropTypes snippets started to add a semicolon at the end. I had default config.

It worked like this:
```jsx
Comp.propTypes = {
   isOpen: ptb -> PropTypes.bool,
}
```
While became:
```jsx
Comp.propTypes = {
   isOpen: ptb -> PropTypes.bool;
}
```

I disabled semicolons in settings and they disappeared, but snippets added line break instead:
```jsx
Comp.propTypes = {
   isOpen: ptb -> PropTypes.bool
   *I'm here*
}
```

I tried to enable Prettier in settings but it did no change (however I thought it should fix this as probably it was Prettier who added comma in the first case).

I'm not sure if this behavior is intended, but could you tell me how can I revert initial one and if not possible to not get a line break at least.

**Comment by dsznajder** [comment]
@edvein-rin Fixed in v4.3.1
