### ISSUE TITLE
snippets not working 

### ISSUE THREAD

**Issue by johnwickakash12** [dsznajder/vscode-react-javascript-snippets#226]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Karen1998** [comment]
@johnwickakash12 hey dude. Do u have any news?

**Comment by elmcapp** [comment]
snippets are not registering

**Comment by alxork** [comment]
Hello, same here, ES7+ React/Redux/React-Native snippets not a single one is working

**Comment by sonterix** [comment]
The same for me. Snippets are not working at all

**Comment by enochmk** [comment]
The same for me. I've uninstalled and installed couple of times no change. I heavily depend on this extension. It's the most useful extension. Hope this is patched soon.

**Comment by jan-vaclavik** [comment]
Same problem. Downgrade to 4.0.1 works for me.

![image](https://user-images.githubusercontent.com/35232007/152528262-6554a00e-3785-4877-9b0b-c3cb9522290a.png)

**Comment by enochmk** [comment]
This works but I'm back with the annoying extra semi colon. Better than nothing. 

> Same problem. Downgrade to 4.0.1 works for me.
> 
> ![image](https://user-images.githubusercontent.com/35232007/152528262-6554a00e-3785-4877-9b0b-c3cb9522290a.png)

**Comment by aindriu80** [comment]
Having trouble too, the underscore wouldn't work - e.g. _rfce so I tried removing the` import react from react ` in settings but that didn't work, then I tried an older version 4.03 but that didn't work so I went back to latest version 4.10 and it no longer does the import React.... however I am getting an extra semi colan 
![2022-02-06_10-26](https://user-images.githubusercontent.com/8885837/152676660-cb794be6-60be-42a1-a81b-083af4edba4c.png)

**Comment by DavidArmendariz** [comment]
Any news on this? They are not working for me neither.

**Comment by Karen1998** [comment]
> Any news on this? They are not working for me neither.

Downgrade to 4.0.1. See images above

**Comment by dsznajder** [comment]
Hello 👋 

I will be reverting prettier auto integration, mark it as experimental and resolve all issues this week. I've been sick past few days so that's why there is that delay. I'm sorry I rushed a little with this update, should test it more on my own. Right now I'm also thinking how I could automate testing to avoid this situations in future. 

Sorry for interrupting your daily workflows.

🖖

**Comment by dsznajder** [comment]
Should be fixed by v4.3.1 @johnwickakash12

**Comment by enochmk** [comment]
> Should be fixed by v4.3.1 @johnwickakash12

It is fixed. I'm loving this update. Good work 👋
