### ISSUE TITLE
Extra semicolon in import snippets

### ISSUE THREAD

**Issue by D1White** [dsznajder/vscode-react-javascript-snippets#230]
Most import snippets (like imp, ima, imd) have a newline and a semicolon. Is there a need for this or is it a bug?
Here is the result of the imd snippet:
`import { second } from 'first';`
`;`

**Comment by ArturoDent** [comment]
Same as https://github.com/dsznajder/vscode-react-javascript-snippets/issues/216

**Comment by D1White** [comment]
I think this should solve the problem #232

**Comment by dsznajder** [comment]
@D1White @ArturoDent fixed in v4.3.0
