### ISSUE TITLE
Git sometimes fails to load with extension enabled

### ISSUE THREAD

**Issue by Wynston** [dsznajder/vscode-react-javascript-snippets#231]
I'm not sure if its due to the load time of this extension but Git fails to load occasionally for me. On average it takes about 900ms for this extension to load, and disabling it seems to resolve my Git problem.

![Screen Shot 2022-02-02 at 9 54 53 AM](https://user-images.githubusercontent.com/23458594/152189647-4f963d72-06aa-4196-a077-2cf4c95447f1.png)

**Comment by dsznajder** [comment]
@Wynston I'm currently working on fixing that, and avoiding prettier formatting for now as it's kinda buggy for some of the snippets. I have some work already done around that and will try to push it forward this weekend.

**Comment by Wynston** [comment]
Awesome, thanks for the speedy reply @dsznajder :D

**Comment by dsznajder** [comment]
@Wynston Let me know if v4.3.0 fixed this.

**Comment by Wynston** [comment]
Sorry I was meaning to get back to you on this.  I'm not totally convinced this issue is solely caused by this plugin now:

I started experiencing the same issue again even though this plugin is disabled 🤔  I wonder if there's a performance concern when VSCode is booting and there are too many extensions enabled. I have about 15 extension at the moment which seems like a lot but is kinda necessary being that I work in a monorepo.

I tried re-installing, adding several locations to my `git.path`, to no prevail; disabling all extensions does seem to work which isn't really a viable solution 😅

**Comment by dsznajder** [comment]
@Wynston previously I was generating and parsing those snippets on the fly. Right now it's a little bit more optimised as I removed prettier integration by default. I will still investigate how to optimise it further. There is also extension to debug startup times. Failures could be also debugged by `Developer Tools` inside VSCode
