### ISSUE TITLE
Snippet return has no braces

### ISSUE THREAD

**Issue by levinaHR** [dsznajder/vscode-react-javascript-snippets#234]
Snippets like rfc, rcc, rafc and such returns <_div_></_div_> in a single line without braces like this:
export default function Content() {
  return <_div_></_div_>
}

Is there any way to change it to this format?
export default function Content() {
   return (
     <_div_></_div_>
   )
}

Also for some reason even if I enable prettier integration it won't work. For example if i disable semicolon in Prettier and keep the ES7 React semicolon enabled, the snippet will still have semicolon.

**Comment by dsznajder** [comment]
@levinaHR I made change to this, let me know if this is fixed by v4.3.1

**Comment by levinaHR** [comment]
It's fixed now, thank you!
