### ISSUE TITLE
React 17 no longer needs React to be in scope

### ISSUE THREAD

**Issue by kylelamse** [dsznajder/vscode-react-javascript-snippets#237]
With the release of React 17, is there going to be support for snippets that exclude the `import React from 'react';` statement from the top?  There could possibly be an option to detect what version is in the project, and automatically disable adding this.  As of now, my editor grays out the statement and displays a warning.
![image](https://user-images.githubusercontent.com/9343089/153299799-0f19c4ad-e841-4d1e-a537-7e05e59c0d72.png)

**Comment by dsznajder** [comment]
@kylelamse take a look at options. There is `import React on Top` checkbox. After extension initialisation (i.e. open javascript/typescript file). Go to your settings, uncheck it and restart VSCode. Those snippets should't have this import from now on.
