### ISSUE TITLE
TypeScript props settings have no effect

### ISSUE THREAD

**Issue by john-TC** [dsznajder/vscode-react-javascript-snippets#238]
The settings `reactSnippets.settings.typescript` and `reactSnippets.settings.typescriptPropsStatePrefix` have no effect in `.tsx` files.

Line 3 should be removed or have `interface` keyword.

Snippet: `tsrafce`
![image](https://user-images.githubusercontent.com/35880688/153350931-69e1674e-49c1-4d34-89f2-9c54938f7287.png)

Awesome extension btw.

**Comment by john-TC** [comment]
So today I changed a setting and a pop up in the bottom right said please reload to apply extension settings. Now I can't change `interface` back to `type`. No pop ups. Changing `settings.json` doesn't do anything. Executing `Reload Window` from the command palette does nothing. Tried installing and uninstalling.

**Comment by dsznajder** [comment]
@john-TC The tricky part with extension activation, it has to be enabled to generate those snippets with options. So first, try to open typescript file, then change option and restart your vscode.

**Comment by john-TC** [comment]
So I opened a blank instance of VS Code, created a new file with `ctrl + n`, changed the language mode to TypeScript, and changed a setting. It worked and got the pop up to restart VS Code.

![image](https://user-images.githubusercontent.com/35880688/153629267-9726a83f-4dd1-46f5-ad53-218ee944856b.png)

It's a problem with VS Code and not with the extension. Thanks for the tip.

**Comment by john-TC** [comment]
Is it possible to detect settings changes with `.tsx` files and not only `.ts`?

**Comment by dsznajder** [comment]
@john-TC it detects `javascript,javascriptreact,typescript,typescriptreact` as language so it will activate on both `.ts` and `.tsx`
