### ISSUE TITLE
Suggestions/Snippets stopped working from 4.4.0

### ISSUE THREAD

**Issue by rpayeras** [dsznajder/vscode-react-javascript-snippets#242]
Hi! suggestions have stopped working since last update (rafc), with 4.3.2 now it works perfectly. Im using vs code on ubuntu 20.04, i have also emmet with "javascript: javascriptreact" enabled from last days if it helps. 
Im been changing some emmet options without result from another issues that I have seen here.

Thanks for your awesome work!

**Comment by asdf1414** [comment]
Same problem for me too. Suggestions and snippets no longer work for me either on Windows 10, VsCode v1.64.2, Extension v4.4.0

**Comment by dsznajder** [comment]
@rpayeras should be fixed in v4.4.3
