### ISSUE TITLE
jsx attribute auto completion (auto option) not working after certain prop type, but works before it 

### ISSUE THREAD

**Issue by NikolaKrsticFFWD** [dsznajder/vscode-react-javascript-snippets#248]
`backgroundColor` successfully auto completed to `backgroundColor=""` before `imgStyle={{position:"absolute"}}`
![image](https://user-images.githubusercontent.com/95031295/157642390-06598a8c-cec3-40f3-bde1-8c0b9ee2e1e5.png)

but it fails to auto complete after the `imgStyle={{position:"absolute"}}`

![image](https://user-images.githubusercontent.com/95031295/157642830-025d1c20-bd2a-47c3-aff4-032b395e5aad.png)

the same is happening with the other prop type:

![image](https://user-images.githubusercontent.com/95031295/157643270-d42cd7d2-02ae-4ad5-b33e-0faa32e1eda4.png)

![image](https://user-images.githubusercontent.com/95031295/157643292-35437bec-8115-4110-b4bc-7362986e2c7d.png)

**Comment by dsznajder** [comment]
@NikolaKrsticFFWD why should this extension cover this? It's because of types in libraries, not by extension for snippets 😅
