### ISSUE TITLE
React 17  workaround doesn't work anymore

### ISSUE THREAD

**Issue by radoRandriamahandry** [dsznajder/vscode-react-javascript-snippets#249]
Hi,
I don't know if it's because of the Win 11 update or VSCode but using "_" doesn't work anymore. eg : _rfce shows nothing.
Thank you.

**Comment by dsznajder** [comment]
@radoRandriamahandry there is no `_`. Instead you have settings for react top import.

**Comment by radoRandriamahandry** [comment]
Ok, didn't read the doc, Thank you for your help.
