### ISSUE TITLE
_rafce not working

### ISSUE THREAD

**Issue by forinda** [dsznajder/vscode-react-javascript-snippets#252]
I loved the template created without necessarily  having `import React from  "react"`
In thelatest version that seems to have gone away but it was really amazing crating the functional components with that snippet.
I'm just requesting if the feature could be revived again
i.e
```js
const App = () =>{
return <div>App</app>
}

export default App
```
### instead of 
```js
import React from "react"
const App = ()=>{
return <div>App</app>
}
export default App
```

**Comment by dsznajder** [comment]
#249 #220 #221 #215 duplicate
